### ISSUE TITLE
Trazz's mystical magical Mages

### ISSUE THREAD

**Issue by Trazz666** [shyzus/Legacy#6]
(Edit: Due to the gender connotation of the names witch and wizard, the good and evil classes of Mage/Magus will be referred to as Purus and Malum respectively. At least in this documentation, because I think the names sound cool.)

This is a listing of Purus and Malum skills I'd like to see implemented into the game, as well as their function. At times, it may seem that these skills are a little over powered, and that Malum may have a few more tricks than Purus. This is by design, since everything has a magical cost, and Magus will be weak as shit in a fight. Malum also have the added disadvantage of being evil, thus targeted by white knights. Listed in no particular order.

**General skills** (for both classes)

- Item Craft: Creates non-magical items such as weights, armor, weapons, and clothes. Things effected by quality (such as weights) require a higher energy cost that scales to the weight/quality.

- Fabricate: Creates magical items such as contracts and crystal balls.

- Observe: Allows observing with a crystal ball. Potentially allows listening to target and small radius.

- Portal: Creates a portal to the AL. Purus to AL, Malum to Hell. Can potentially be made permanent.

- Teleport: Teleports mage to desired planet (main planets only).

- Invisibility: Turn invisible at cost of energy drain. Dissipates when attacked, attacking, or running out of power.

- Grant Invisibility: Stores a 1 time use minor invisibility on a character. Mage does not regain energy until spell is used.

- Grant Teleportation: Stores a 1 time use teleportation on a character. Mage does not regain energy until spell is used.

- Spell revoke: Resets all stored spells

**Purus skills**

- Cleanse Aura: Begins process of increasing target's aura on the good/evil axis. Long process, uses considerable amount of energy.

- Give mystic: Gives mystic.

- Bless: Boosts target's stats, constant energy drain. Must maintain concentration.

- Heal: Exchanges magical energy for vitality. Must maintain concentration. Will have to figure out balanced ratio of energy-to-vitality to keep it from being OP. May have time limit to keep it from being spammed in battle.

- Restoration: Speeds up natural healing process for long term injuries. Mage does not regain energy until healing period is complete. Heals fractured/broken bones, may restore missing limbs at increased magical cost.

**Malum Skills**

- Corrupt Aura: Begins process of decreasing target's aura on the good/evil axis. Long process, uses considerable amount of energy.

- Summon: Brings contracted soul/Demon to your location.

- Give majin: Gives/forces majin. Different tiers costs different amounts for desired effect. (will discuss later)

- Curse: Drains target's stats, constant energy drain. Must maintain concentration.

- Dominate: Assume control over Majinized character.

- Majin Destruction (rare skill): Causes energy overload in majinized character, self destructing.

**Fabricated Items**

- Crystal Ball: Allows casting of spells.

- Energy Drain Device: Can be used to drain energy. 

- Cruel Energy Drain Device: Can be used to cruelly drain energy.

- Energy Battery: Stores drained energy from EDD/CEDD.

- Energy Tank: Stores massive amount of energy. Cannot be carried in inventory outside of capsule.

- Purus Contract: Allows contracted soul/Kai to use portals for 1 hour

- Malus Contract: Allows contracted soul/demon to use portals for 1 hour

- Malus Soul Contract: Binds soul/demon to your service. Permanent portal use, can be summoned.

- Health potion: Restores HP. HP is scaled to energy used to create -cost of casting.

- Energy Capsule: Restores energy. Energy is scaled to energy used to create -cost of casting.

**Comment by Trazz666** [comment]
**Majin Details**

Just like in DBG, Majin will be based on a 3 tiered system. 

- Level 1 is a minor power boost, and RPs as an allegiance to your wizard. (Technically your thoughts are your own, but you shouldn't go disobeying/killing your wizard without a serious reason).

- Level 2 is a moderate power boost, and RPs as your wizard has infiltrated half of your brain/thoughts.

- Level 3 is a massive power boost, and RPs as total domination.

The perks of Majinization (besides the power) include: Free telepathy between you and your wizard, your wizard can observe and hear you no matter the distance/plane difference, free sensing of your master (as long as you have sense and are on the same planet), you act as a contracted creature for the purposes of portal usage and summonability.

Now, about the tiers of casting. As the energy/magic system has not been set up, Magic Points or 'MP' will be used as a placeholder to represent a wizards magic resource. When casting Majin, your target will be presented with 3 options: Resist, Pretend (to accept), and Accept. Their level of Majinization will depend on your level of casting, their response, and your desired effect (optional).

- Cast at level 1 (100,000 MP): Resist; Target gets Majin 1. Pretend; Target gets Majin 2. Accept; Target gets Majin 3.

- Cast at level 2 (200,000 MP): Resist: Target gets Majin 2. Pretend; Target gets Majin 3. Accept; Target gets Majin 3.

- Cast at level 3 (400,000 MP): Resist; Target gets Majin 3. Pretend; Target gets Majin 3. Accept; Target gets Majin 3.

After the casting, you become aware of the level of Majinization. If at any point, your target/victim chooses Majin 2 or 3, you may select to grant them any lower level of your choosing to fit your RP wants/needs. In this way, it rewards wizards for RPing with their targets for long periods of time to gain their trust before casting Majin at level 1 to save on the _massive_ MP cost, but also allows well established wizards to spend the resources to subjugate a powerful target to their whims (should they be willing to invest the massive amount of resources).

At level 1, you may allow your wizard to dominate you through a prompt. At level 2, you are given the prompt, but if you deny there is a 50% chance the wizard succeeds anyways. At level 3 you are offered no choice. Majin Destruction may only be cast on a level 3 Majin.

As a note, a dead wizard means the release of all Majinized targets.

**Comment by Trazz666** [comment]
Also, side-note: The difference between a normal energy drain vs. a 'cruel' energy drain via the Wizard Energy Storage Device is such.

- A standard energy drain takes 10%* of a target's energy/PL, which restores in 1 IC year.

- A cruel energy drain takes 50-75%* of a target's energy/PL permanently

*all numbers are estimations at this time, as stated before the system has not been fleshed out and is prone to balancing.

**Comment by Matokushin** [comment]
I feel like they should be able to teleport to any Planet they have been to before. They seem to have no limitations in the anime as Babidi went to the Demon Realm to majin Dabura he also teleported around the universe with Majin Buu to destroy multiple planets and civilizations. Baba could go to the afterlife and I'm sure both can go where they please if they have the requirements to do so.

I don't know how I feel about the cleansing aura thing, I feel like it shouldn't be because Baba wasn't seen cleansing aura. The fact the people would abuse this on their friends or purposely, foolishly mis-use it. Same for wizards corrupting aura. People can just get alignment adjusts from admins or however Neg will set it up.

I'm fine with everything else however, the cruel drain shouldn't permanently take away pl/energy as it didn't do it in DBG. (If this was what you were aiming for.) It simply 'hid' a fuck load of your Body % which sloowwly went up overtime. So basically it hid a vast majority of your power for a long time. I believe like 2 years or some at the most..?

**Comment by Matokushin** [comment]
Witches should be given the option to 'One-Day Revive'. Which only lasts for like 45 minutes maybe 30 since a month was 45 minutes in DBG.

**Comment by Trazz666** [comment]
I don't think witches should be able to revive, that'd be a waaay too easy way to circumvent death and feels kinda cheap. I'm also fine with teleporting to any planet you've been to, but if we're adding a shit-load of planets...I mean, maybe there's a way to make the UI for that feel fluid so you can still go where you want in an emergency.

For the drain thing, it wouldn't effect your mods. So if a wizard doesn't decide to kill you after a cruel drain, you can still regain up to your full % with training.

As for the aura cleanse/corrupt, I maintain that it's something I want in. The way I picture it, to influence someone's aura it's a process that takes 5-10 IC years, and during the process the wizard has severely stunted energy (I'm thinking somewhere in the range of 50%). I see it as a way of cultivating a student, or pulling an Emperor Palpatine and prepping someone to be majinized weither they like it or not. I don't exactly like admins changing someone's aura, and I doubt the admins will change someone else's aura without the other player's consent.

And also, I realize this is abusable, but I feel anyone caught abusing witches/wizards should be banned from using the race, since they do have the potential to be very powerful.

**Comment by Trazz666** [comment]
I should also mention I don't intend on the witch's cleansing to be as powerful as the corrupting. The witch's cleansing is really meant to delay/stop the wizards corrupting if it's detected. That also prevents people from spam cleansing or forcing a witch to cleanse you to hide your evil intent effectively.

**Comment by Trazz666** [comment]
Posts updated to reflect racial/class name changes.

I should also clarify, in my reply to Mato I said Purus shouldn't be able to revive, but in the Reincarnation post I said they should. That was a mistake on my part. I _do_ think both Mage classes should be allowed a revive skill (I've yet to decide if it should be rare to learn or not). As with all Mage spells it will have an energy cost, and just like any revival attempts done in the mortal plane, there is a time limit to perform it (body decay). I also mentioned Purus would have to select someone to sacrifice themselves to take the dead's place, and Malum will be able to enslave the revived similar to Majinization. With these draw-backs, I'm hoping to limit Mage revival as a last attempt type deal, and make it a dire situation scenario to justify it's use. (I also think Malum should be restricted to reviving/enslaving evil souls only, just so it can't be used for everybody with decent muscle)
